FROM golang:1.26-alpine

WORKDIR /app
RUN apk add --no-cache git

# Install Air (hot reload)
RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download
COPY . .

EXPOSE 8000
CMD ["air"]